///FOR MANAGER
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const ADD_SUCCESS = "ADD_SUCCESS";
export const REMOVE_SUCCESS = "REMOVE_SUCCESS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CREATE_USER_INFORMATION = "CREATE_USER_INFORMATION";
export const LOAD_USER_INFORMATION = "LOAD_USER_INFORMATION";

export const CREATE_CO_QUAN_QUAN_LY = "CREATE_CO_QUAN_QUAN_LY";
export const LOAD_CO_QUAN_QUAN_LY = "LOAD_CO_QUAN_QUAN_LY";
export const UPDATE_CO_QUAN_QUAN_LY = "UPDATE_CO_QUAN_QUAN_LY";
export const REMOVE_CO_QUAN_QUAN_LY = "REMOVE_CO_QUAN_QUAN_LY";

export const CREATE_CO_SO_DAO_TAO = "CREATE_CO_SO_DAO_TAO";
export const LOAD_CO_SO_DAO_TAOS = "LOAD_CO_SO_DAO_TAOS";
export const UPDATE_CO_SO_DAO_TAO = "UPDATE_CO_SO_DAO_TAO";
export const REMOVE_CO_SO_DAO_TAO = "REMOVE_CO_SO_DAO_TAO";

export const CREATE_NHOM_KHOA_HOC = "CREATE_NHOM_KHOA_HOC";
export const LOAD_NHOM_KHOA_HOC = "LOAD_NHOM_KHOA_HOC";
export const UPDATE_NHOM_KHOA_HOC = "UPDATE_NHOM_KHOA_HOC";
export const REMOVE_NHOM_KHOA_HOC = "REMOVE_NHOM_KHOA_HOC";

export const CREATE_KHOA_HOC = "CREATE_KHOA_HOC";
export const UPDATE_KHOA_HOC = "UPDATE_KHOA_HOC";
export const REMOVE_KHOA_HOC = "REMOVE_KHOA_HOC";



// export const CREATE_KHOA_HOC = "CREATE_KHOA_HOC";
// export const LOAD_KHOA_HOC = "LOAD_KHOA_HOC";
// export const UPDATE_KHOA_HOC = "UPDATE_KHOA_HOC";
// export const REMOVE_KHOA_HOC = "REMOVE_KHOA_HOC";

export const LOAD_CO_SO_DAO_TAO = "LOAD_CO_SO_DAO_TAO";

export const CREATE_CO_SO_VAT_CHAT = "CREATE_CO_SO_VAT_CHAT";
export const UPDATE_CO_SO_VAT_CHAT = "UPDATE_CO_SO_VAT_CHAT";
export const DELETE_CO_SO_VAT_CHAT = "DELETE_CO_SO_VAT_CHAT";

export const CREATE_GIANG_VIEN = "CREATE_GIANG_VIEN";
export const UPDATE_GIANG_VIEN = "UPDATE_GIANG_VIEN";
export const DELETE_GIANG_VIEN = "DELETE_GIANG_VIEN";

export const CREATE_TAI_LIEU = "CREATE_TAI_LIEU";
export const UPDATE_TAI_LIEU = "UPDATE_TAI_LIEU";
export const DELETE_TAI_LIEU = "DELETE_TAI_LIEU";

export const CREATE_OR_UPDATE_LIEN_HE = "CREATE_OR_UPDATE_LIEN_HE";

export const UPDATE_CHI_TIET_KHOA_HOC = "UPDATE_CHI_TIET_KHOA_HOC";
export const ACTIVE_KHOA_HOC = "ACTIVE_KHOA_HOC";

export const ADD_BAI_HOC = "ADD_BAI_HOC";
export const UPDATE_BAI_HOC = "UPDATE_BAI_HOC";
export const REMOVE_BAI_HOC = "REMOVE_BAI_HOC";

export const ADD_BAI_KIEM_TRA = "ADD_BAI_KIEM_TRA";
export const UPDATE_BAI_KIEM_TRA = "UPDATE_BAI_KIEM_TRA";
export const REMOVE_BAI_KIEM_TRA = "REMOVE_BAI_KIEM_TRA";

export const ADD_LOP_HOC = "ADD_LOP_HOC";
export const UPDATE_LOP_HOC = "UPDATE_LOP_HOC";
export const REMOVE_LOP_HOC = "REMOVE_LOP_HOC";

///FOR GUEST
export const GUEST_LOAD_CO_SO_DAO_TAOS = "GUEST_LOAD_CO_SO_DAO_TAOS";
export const GUEST_CURRENT_USER = "GUEST_CURRENT_USER";

export const DANG_KY_HOC = "DANG_KY_HOC";
export const PASS_KHOA_HOC = "PASS_KHOA_HOC";
export const UPDATE_KHOA_HOC_DANG_KY = "UPDATE_KHOA_HOC_DANG_KY";

export const LOAD_BAI_HOC = "LOAD_BAI_HOC";
export const LOAD_BAI_KIEM_TRA = "LOAD_BAI_KIEM_TRA";

export const LOAD_KHOA_HOC = "LOAD_KHOA_HOC";

export const SEARCH_USER_BY_NAME = "SEARCH_USER_BY_NAME";
export const SEARCH_KHOA_HOC_BY_NAME = "SEARCH_KHOA_HOC_BY_NAME";
